### ISSUE TITLE
Seed date error

### ISSUE THREAD

**Issue by kennyhyun** [kennyhyun/word-resume#2]
v0.9.8
from and to are opposite in an experience.

sample.yml

```yaml
header:
  author: Kenneth Welch
  title: Resume
  description: sample seed data generated by seed
  paragraphs:
    - source: profile
      title: $name
    - source: workHistory
      title: Work History
      first: 6
      digestRest: true
    - source: educationHistory
      title: Education
      first: 4
    - source: language
      title: language
data:
  profile:
    name: Kenneth Welch
    title: Technical Support Specialist
    email: punjenjem@mej.ru
    address: 1383 Wosba Highway
    phone: (413) 490-8374
    carrierSummary:
      default: >-
        Uvgitin cej iz pela tihumife ogiheor ownome pelabu vajcezep hiloliru fo
        iburi ca fezeze kojo muf. Pat germibpen lu wuubebog igtupene en tiv wet
        asu nomrak gamkid he fubivam fo zense.
      frontend: >-
        Lujafzi zov efva mejete zimiddal zi nemewdih god ipejikemi zo ejocoze
        rorzi anaf di za ka. Bazemuso bosi rotparen efe to cidfekoh foit tapnoir
        etap pek wu roli joelbi puwle bavi jeib setidu.
    technicalSkills:
      programmingLanguages:
        - gaflang
        - bulang
        - dezlang
      generalOfficeSkills:
        - zedami
        - zorenuf
        - bagublu
        - va
        - hipba
        - nunno
        - razu
  workHistory:
    - company: Textron Inc
      location: Igorubij
      type: contract
      duration: 18 Jun 2017 ~ 04 May 2015
      title: Technical Support Specialist
      field: Zehaju edi iloluum.
      achievements:
        - Pondume hejib zuwzesa he ipe hera laose gih ve imo su ow fes.
        - Ogi ki ogowotzem sin de kas matmu sa no ekunuzgi vuwpu wod ob.
        - >-
          Firefsof ganew evice rok avsi es unga bi zemfuul pe havuwa fukrurto
          vi.
      skills:
        - vommo
        - pezu
        - lo
        - win
        - hinonab
    - company: Gentiva Health Services Inc.
      location: Hucajer
      type: permanent
      duration: 04 May 2015 ~ 02 Aug 2014
      title: Technical Support Specialist
      field: Op vehuj jidacibot.
      achievements: []
      skills:
        - hanowe
        - loddunhin
        - azvavtew
        - eksu
        - 'on'
        - fimmicez
    - company: Trump Hotels & Casino Resorts Inc.
      location: Bajmepij
      type: permanent
      duration: 02 Aug 2014 ~ 22 Mar 2014
      title: Technical Support Specialist
      field: Kohfahmu iceor fidij.
      achievements:
        - >-
          Ampahul rorgijwa uzuaba jubmado jumaop veb sohjew aka filogaj aga
          bijoden camra wumotmig.
      skills:
        - ricli
        - dejba
        - divire
        - zihlap
    - company: CMS Energy Corp.
      location: Ohkaju
      type: permanent
      duration: 22 Mar 2014 ~ 01 Jun 2011
      title: Technical Support Specialist
      field: Cegecet nuasgew bimoz.
      achievements:
        - >-
          Aguuju avlame sozezugug lo helog awunakew ojewuhi teorho adhaj kivju
          dusa noita hu.
        - >-
          Curjumheb da kipar afa kofwi ub ducuv vuholaw goag rab bidec hoavuig
          tened.
      skills:
        - jukdov
        - bes
        - juukec
        - cusu
        - rahi
        - lon
        - icaef
    - company: Reliant Energy Inc.
      location: Nagammew
      type: contract
      duration: 01 Jun 2011 ~ 29 Apr 2011
      title: Technical Support Specialist
      field: Kupewzim kemiwfu pod.
      achievements:
        - >-
          Zonuuj kejerzog kencum fesjo dimneg pocbipho viwud tonbasego ufpu
          tozor uli eku rilun.
        - >-
          Him escaaw nokiki pin zanuf tejugfaf kahulruz hifuzluj ut has ga
          jiwopa icijjew.
        - >-
          Wa la bofdabu jifo kadwef ucizi lidjefbu bivmuzce uvali pibheh oji
          jofvej fedtukpes.
      skills:
        - korepug
        - roja
        - redtu
        - gowfilges
        - lepu
        - uni
        - nunropes
  educationHistory:
    - institute: Dofutav University
      major: Technical Support Specialist Engineering
      location: 'Gapohkag, NZ'
      duration: Apr 2011
      title: Bachelor of Engineering
      acquisition: Nov 2009
  language:
    - Umbrella Squidese
    - Krillese
    - Bantengese
```
Rendered as 

[Kenneth Welch-05Nov2018.pdf](https://github.com/kennyhyun/word-resume/files/2546811/Kenneth.Welch-05Nov2018.pdf)
[Kenneth Welch-05Nov2018.docx](https://github.com/kennyhyun/word-resume/files/2546812/Kenneth.Welch-05Nov2018.docx)

check the attaches
